MQTTWebApp/Controllers/TopicManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MongoAccess.DataAccess;
using MongoAccess.Model;
using MongoDB.Driver;
using MQTTTopicManager;

namespace MQTTWebApp.Controllers
{
    //[ApiController]
    // [Route("api/[controller]")]
    public class TopicManagerController : Controller
    {
        private readonly ILogger<TopicManagerController> _logger;
        private readonly DeviceMongoDriver<DeviceObject> _deviceMongoDriverDeviceObject;
        private readonly DeviceMongoDriver<TimeSeriesObject> _deviceMongoDriverTimeSeriesObject;
        private readonly ITopicManager _topicManager;


        public TopicManagerController(ILogger<TopicManagerController> logger, DeviceMongoDriver<DeviceObject> deviceMongoDriverDeviceObject, DeviceMongoDriver<TimeSeriesObject> deviceMongoDriverTimeSeriesObject, ITopicManager topicManager)
        {
            _logger = logger;
            _deviceMongoDriverDeviceObject = deviceMongoDriverDeviceObject;
            _deviceMongoDriverTimeSeriesObject = deviceMongoDriverTimeSeriesObject;
            _topicManager = topicManager;
            //  _topicManager.ConnectMqttClientAsync();
        }
        public IActionResult Dashboard()
        {
            return View();

            // return Json(new { mytest = DateTime.Now.ToString("h:mm:ss tt") });
        }
        public IActionResult AutoSelectDemo()
        {
            return View();
        }
        public IActionResult Status()
        {
            return View();
        }
        public IActionResult Battery()
        {
            return View();
        }

        public IActionResult Temperature()
        {
            return View();
        }


        #region APIs
        [HttpGet]
        public string CampusList()
        {
            // var campusList = _deviceMongoDriverDeviceObject.Collection.AsQueryable().Select(c => new { c.Campus }).Distinct().ToList();
            //  return JsonSerializer.Serialize(campusList.ToList());
            return _topicManager.GetAllCampusList();
        }

        /*  [HttpGet]
          public string BuildingList(string campus)
          {
              //  if (!String.IsNullOrEmpty(campus))
              //   _topicManager.SetSelecter(campus, 1);


              //   var buildingList = _deviceMongoDriverDeviceObject.Collection.AsQueryable().Where(c => c.Campus == campus).Select(c => new //{ c.Building }).Distinct().ToList();
              //   return JsonSerializer.Serialize(buildingList.ToList());
              return _topicManager.GetAllBuildingList(campus);
          }*/

        [HttpGet]
        public string MultipleBuildingList(string campusList)
        {
            //  if (!String.IsNullOrEmpty(campus))
            //   _topicManager.SetSelecter(campus, 1);                   

            //   var buildingList = _deviceMongoDriverDeviceObject.Collection.AsQueryable().Where(c => c.Campus == campus).Select(c => new //{ c.Building }).Distinct().ToList();
            //   return JsonSerializer.Serialize(buildingList.ToList());
            return _topicManager.GetMultipleSelectionBuildingList(campusList);
        }

        [HttpGet]
        public string MultipleSelectionConfigList(string input)
        {
            //  if (!String.IsNullOrEmpty(campus))
            //   _topicManager.SetSelecter(campus, 1);                   

            //   var buildingList = _deviceMongoDriverDeviceObject.Collection.AsQueryable().Where(c => c.Campus == campus).Select(c => new //{ c.Building }).Distinct().ToList();
            //   return JsonSerializer.Serialize(buildingList.ToList());
            return _topicManager.GetMultipleSelectionConfigList(input);
        }

        [HttpGet]
        public string MultipleRoomList(string buildingList)
        {
            //  if (!String.IsNullOrEmpty(campus))
            //   _topicManager.SetSelecter(campus, 1);                   

            //   var buildingList = _deviceMongoDriverDeviceObject.Collection.AsQueryable().Where(c => c.Campus == campus).Select(c => new //{ c.Building }).Distinct().ToList();
            //   return JsonSerializer.Serialize(buildingList.ToList());
            return _topicManager.GetMultipleSelectionRoomList(buildingList);
        }

        /*    [HttpGet]
            public string RoomList(string building)
            {
                // if (!String.IsNullOrEmpty(building))
                //     _topicManager.SetSelecter(building, 2); 

                //  var roomList = _deviceMongoDriverDeviceObject.Collection.AsQueryable().Where(c => c.Campus == _topicManager.GetSelecter(1) && c.Building == _topicManager.GetSelecter(2)).Select(c => new { c.Room }).Distinct().ToList();
                //   return JsonSerializer.Serialize(roomList.ToList());
                return _topicManager.GetAllRoomList(building);
            }
            [HttpGet]
            public async Task<string> GetRoomData(string room)
            {
                // if (!String.IsNullOrEmpty(building))
                //     _topicManager.SetSelecter(building, 2); 

                //  var roomList = _deviceMongoDriverDeviceObject.Collection.AsQueryable().Where(c => c.Campus == _topicManager.GetSelecter(1) && c.Building == _topicManager.GetSelecter(2)).Select(c => new { c.Room }).Distinct().ToList();
                //   return JsonSerializer.Serialize(roomList.ToList());
                return await _topicManager.GetRoomData(room);
            }*/

        [HttpGet]
        public async Task<string> MultipleRoomListData(string roomList)
        {
            // if (!String.IsNullOrEmpty(building))
            //     _topicManager.SetSelecter(building, 2); 

            //  var roomList = _deviceMongoDriverDeviceObject.Collection.AsQueryable().Where(c => c.Campus == _topicManager.GetSelecter(1) && c.Building == _topicManager.GetSelecter(2)).Select(c => new { c.Room }).Distinct().ToList();
            //   return JsonSerializer.Serialize(roomList.ToList());
            return await _topicManager.MultipleRoomListData(roomList);
        }
        [HttpGet]
        public string GetHolidayList()
        {
            return _topicManager.GetHolidayList();
        }

        [HttpGet]
        public async Task<string> GetWarningList()
        {
            // if (!String.IsNullOrEmpty(building))
            //     _topicManager.SetSelecter(building, 2); 

            //  var roomList = _deviceMongoDriverDeviceObject.Collection.AsQueryable().Where(c => c.Campus == _topicManager.GetSelecter(1) && c.Building == _topicManager.GetSelecter(2)).Select(c => new { c.Room }).Distinct().ToList();
            //   return JsonSerializer.Serialize(roomList.ToList());
            return await _topicManager.GetWarningList();
        }


        [HttpGet]
        public async Task<string> GetAddSensorJson()
        {
            // if (!String.IsNullOrEmpty(building))
            //     _topicManager.SetSelecter(building, 2); 

            //  var roomList = _deviceMongoDriverDeviceObject.Collection.AsQueryable().Where(c => c.Campus == _topicManager.GetSelecter(1) && c.Building == _topicManager.GetSelecter(2)).Select(c => new { c.Room }).Distinct().ToList();
            //   return JsonSerializer.Serialize(roomList.ToList());
            return await _topicManager.GetAddSensorJson();
        }

        [HttpGet]
        public async Task<string> GetChartsList()
        {
            // if (!String.IsNullOrEmpty(building))
            //     _topicManager.SetSelecter(building, 2); 

            //  var roomList = _deviceMongoDriverDeviceObject.Collection.AsQueryable().Where(c => c.Campus == _topicManager.GetSelecter(1) && c.Building == _topicManager.GetSelecter(2)).Select(c => new { c.Room }).Distinct().ToList();
            //   return JsonSerializer.Serialize(roomList.ToList());
            return await _topicManager.GetChartsList();
        }

        [HttpGet]
        public async Task<string> GetSensorStatus()
        {
            // if (!String.IsNullOrEmpty(building))
            //     _topicManager.SetSelecter(building, 2); 

            //  var roomList = _deviceMongoDriverDeviceObject.Collection.AsQueryable().Where(c => c.Campus == _topicManager.GetSelecter(1) && c.Building == _topicManager.GetSelecter(2)).Select(c => new { c.Room }).Distinct().ToList();
            //   return JsonSerializer.Serialize(roomList.ToList());
            return await _topicManager.GetSensorStatus();
        }


        [HttpGet]
        public async Task<string> GetCountCards()
        {
            // if (!String.IsNullOrEmpty(building))
            //     _topicManager.SetSelecter(building, 2); 

            //  var roomList = _deviceMongoDriverDeviceObject.Collection.AsQueryable().Where(c => c.Campus == _topicManager.GetSelecter(1) && c.Building == _topicManager.GetSelecter(2)).Select(c => new { c.Room }).Distinct().ToList();
            //   return JsonSerializer.Serialize(roomList.ToList());
            return await _topicManager.GetCountCards();
        }


        [HttpGet]
        public async Task<string> GetSensorData()
        {
            // if (!String.IsNullOrEmpty(building))
            //     _topicManager.SetSelecter(building, 2); 

            //  var roomList = _deviceMongoDriverDeviceObject.Collection.AsQueryable().Where(c => c.Campus == _topicManager.GetSelecter(1) && c.Building == _topicManager.GetSelecter(2)).Select(c => new { c.Room }).Distinct().ToList();
            //   return JsonSerializer.Serialize(roomList.ToList());
            return await _topicManager.GetSensorData();
        }

        [HttpGet]
        public async Task<string> GetSensorDataCustom(int date, string JSONSensorList)
        {
            // if (!String.IsNullOrEmpty(building))
            //     _topicManager.SetSelecter(building, 2); 

MQTTWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - La Trobe University NetZero Smart HVAC </title>


    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <!--
     <link rel="stylesheet" href=https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

     <link rel="stylesheet" href=https://use.fontawesome.com/releases/v5.6.3/css/all.css integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
     <link rel="stylesheet" href=https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.css>
     -->
    <link rel="stylesheet" href="~/css/all.css" />
    <link rel="stylesheet" href="~/css/bootstrap-table.min.css" />
    <link rel="stylesheet" href="~/css/FunButton.css" />

    @RenderSection("Links", required: false)

    <!--  Links {
         <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
         <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" />
         <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
         <link href="https://unpkg.com/tabulator-tables@4.9.3/dist/css/tabulator.min.css" rel="stylesheet">
     }-->
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.css" rel="stylesheet">
</head>

<body>
    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">La Trobe University NetZero Smart HVAC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TopicManager" asp-action="Dashboard">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TopicManager" asp-action="AutoSelectDemo">Alert</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TopicManager" asp-action="Status">Status</a>                    
                        <li class="nav-item dropdown">
                            <a class="nav-link  text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Chart
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TopicManager" asp-action="Battery">Battery</a>
                                <a class="nav-link  text-dark" asp-area="" asp-controller="TopicManager" asp-action="Temperature">Temperature</a>                          
                            </div>
                        </li>
                        <!--
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="TopicManager" asp-action="charts">Monitor</a>
    </li>-->

                    </ul>
                </div>
                <img src=https://www.latrobe.edu.au/_media/la-trobe-api/v5/img/latrobe-logo-og.png alt="Logo image" width="200" height="100" vertical-align: text-bottom>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 Centre for Technology Infusion La Trobe University - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


   
    <!--

      <script src="~/lib/jquery/dist/jquery.min.js"></script>
      <script src=https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js></script>
      <script src=https://code.jquery.com/jquery-3.6.0.js
            integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
            crossorigin="anonymous"></script>
        -->




    <script src="~/js/jquery-3.6.0.min.js"></script>
    <script src="~/js/jquery-3.6.0.js"></script>

    <script src="~/js/popper.min.js"></script>
    <script src="~/js/jquery-ui.js"></script>
    <script src="~/js/jquery.dataTables.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

    <!--
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>

        <script src=https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js></script>
        <script src=https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js></script>
        <script src=https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/export/bootstrap-table-export.min.js></script>
        <script src=https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table-locale-all.min.js></script>

        <script src=https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <script src=https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js></script>
        <script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.9.3/dist/js/tabulator.min.js"></script>
        <script type="text/javascript" src=" https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.0.5/jspdf.plugin.autotable.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
         -->
    <script src="~/js/tableExport.min.js"></script>
    <script src="~/js/select2.min.js"></script>
    <script src="~/js/jquery-weekdays.js"></script>
  
    <script type="text/javascript" src="~/js/tabulator.min.js"></script>
    <script type="text/javascript" src="~/js/moment.min.js"></script>
    <script src="~/js/jspdf.min.js"></script>
    <script src="~/js/jspdf.plugin.autotable.js"></script>
    <script src="~/js/tippy-bundle.umd.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>